name: 'Setup Java and Maven'
description: 'Setup Java and Maven for pipeline'
inputs:
  artifactory-user-nasa:
    description: 'Artifactory user for NASA'
    required: true
  artifactory-pass-nasa:
    description: 'Artifactory password for NASA'
    required: true
  proxy-host-nb:
    description: 'Proxy host for NB'
    required: true
  proxy-port-nb:
    description: 'Proxy port for NB'
    required: true
  java-version:
    description: 'Java SDK version to use'
    required: false
    default: '21'
  maven-version:
    description: 'Maven version to use'
    required: false
    default: '3.9.5'
runs:
  using: "composite"
  steps:
    - name: Create maven .m2 settings
      uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d
      with:
        servers: '[
          { "id": "snapshots", "username": "${{ inputs.artifactory-user-nasa }}", "password": "${{ inputs.artifactory-pass-nasa }}" },
          { "id": "releases", "username": "${{ inputs.artifactory-user-nasa }}", "password": "${{ inputs.artifactory-pass-nasa }}" }
        ]'
        repositories: '[
          { "id": "central", "url": "https://repo1.maven.org/maven2/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } },
          { "id": "confluent", "url": "https://packages.confluent.io/maven/" },
          { "id": "jitpack", "url": "https://jitpack.io" },
          { "id": "shibboleth", "url": "https://build.shibboleth.net/nexus/content/repositories/releases/" }
        ]'
        proxies: '[
          { "id": "nb-proxy-http", "active": "true", "protocol": "http", "host": "${{ inputs.proxy-host-nb }}", "port": "${{ inputs.proxy-port-nb }}", "nonProxyHosts": "localhost|127.0.0.1|docker"},
          { "id": "nb-proxy-https", "active": "true", "protocol": "https", "host": "${{ inputs.proxy-host-nb }}", "port": "${{ inputs.proxy-port-nb }}", "nonProxyHosts": "localhost|127.0.0.1|docker"}
        ]'
        output_file: 'settings.xml'
    - name: Set up JDK-${{ inputs.java-version }} with cache
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # ratchet:actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: ${{ inputs.maven-version }}