name: 'Kubernetes Deploy'
description: 'Kubernetes Deploy for pipeline'
inputs:
  k8s-server:
    description: 'k8s server'
    required: true
  k8s-certificate-authority-data:
    description: 'k8s certificate authority data'
    required: true
  k8s-user-token:
    description: 'k8s user token'
    required: true
  k8s-user:
    description: 'k8s user'
    required: true
  k8s-context:
    description: 'k8s context'
    required: true
  service-name:
    description: 'Service name'
    required: false
  replicas:
    description: 'Dev replicas'
    required: false
  release-version:
    description: 'Release version'
    required: false
  spring-profiles:
    description: 'Spring profiles'
    required: false
  cmd:
    description: 'Custom deployment command'
    required: false


runs:
  using: "composite"
  steps:
    - name: Kubernetes Deploy
      shell: bash
      run: |
        kubectl config set-cluster k8s --server="${{ inputs.k8s-server }}"
        kubectl config set clusters.k8s.certificate-authority-data ${{ inputs.k8s-certificate-authority-data }}
        kubectl config set-credentials ${{ inputs.k8s-user }} --token="${{ inputs.k8s-user-token }}"
        kubectl config set-context ${{ inputs.k8s-context }} --cluster=k8s --user=${{ inputs.k8s-user }}
        kubectl config use-context ${{ inputs.k8s-context }}
        helm repo add chartmuseum https://tools.nb.no/chartmuseum/
        helm repo update
        
        if [[ -n "${{ inputs.cmd }}" ]]; then
          echo "Running custom command: ${{ inputs.cmd }}"
          eval "${{ inputs.cmd }}"
        fi