name: 'Setup Java and Maven'
description: 'Setup Java and Maven for pipeline'
inputs:
  artifactory-host:
    description: 'Artifactory host'
    required: true
  artifactory-user-nasa:
    description: 'Artifactory user for NASA'
    required: true
  artifactory-pass-nasa:
    description: 'Artifactory password for NASA'
    required: true
  proxy-host-nb:
    description: 'Proxy host for NB'
    required: true
  proxy-port-nb:
    description: 'Proxy port for NB'
    required: true
  cache-endpoint:
    description: 'S3 Cache endpoint'
    required: true
  cache-accessKey:
    description: 'S3 Cache access key'
    required: true
  cache-secretKey:
    description: 'S3 Cache secret key'
    required: true
  cache-bucket:
    description: 'S3 Cache bucket'
    required: true
  java-version:
    description: 'Java SDK version to use'
    required: false
    default: '21'
  maven-version:
    description: 'Maven version to use'
    required: false
    default: '3.9.9'
runs:
  using: "composite"
  steps:
    - name: Create maven .m2 settings
      uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d
      with:
        servers: '[
                { "id": "snapshots", "username": "${{ inputs.artifactory-user-nasa }}", "password": "${{ inputs.artifactory-pass-nasa }}" },
                { "id": "releases", "username": "${{ inputs.artifactory-user-nasa }}", "password": "${{ inputs.artifactory-pass-nasa }}" }
              ]'
        repositories: '[
                { "id": "nbcache", "url": "https://${{inputs.artifactory-host}}/artifactory/libs-release" },
                { "id": "snapshots", "url": "https://${{inputs.artifactory-host}}/artifactory/libs-snapshot-local", "releases": { "enabled": "false" }, "snapshots": { "enabled": "true" } },
                { "id": "releases", "url": "https://${{inputs.artifactory-host}}/artifactory/libs-release-local", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }
              ]'
        proxies: '[
                { "id": "nb-proxy", "active": "true", "protocol": "http", "host": "${{ inputs.proxy-host-nb }}", "port": "${{ inputs.proxy-port-nb }}", "nonProxyHosts": "*.nb.no|docker|localhost|172.*|127.*|[::1]"}
              ]'
        output_file: 'settings.xml'

    - name: Set up JDK-${{ inputs.java-version }} with cache
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # ratchet:actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: Cache
      uses: tespkg/actions-cache@v1
      with:
        endpoint: ${{ inputs.cache-endpoint}}
        accessKey: ${{ inputs.cache-accessKey }}
        secretKey: ${{ inputs.cache-secretKey }}
        bucket: ${{ inputs.cache-bucket }}
        use-fallback: true
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ inputs.maven-version }}-${{ github.ref_name }}-${{ hashFiles('**/pom.xml') }}-${{ github.run_id }}
        restore-keys: |
            ${{ runner.os }}-maven-${{ inputs.maven-version }}-${{ github.ref_name }}-${{ hashFiles('pom.xml', '**/pom.xml') }}-
            ${{ runner.os }}-maven-${{ inputs.maven-version }}-${{ github.ref_name }}-
            ${{ runner.os }}-maven-${{ inputs.maven-version }}-
            ${{ runner.os }}-maven-