name: Build mvn Spring app

on:
  workflow_call:
    outputs:
      build-tag:
        description: "Build tag"
        value: ${{ jobs.build-app.outputs.build-tag }}
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '21'

jobs:
  build-app:
    name: Build app
    runs-on: self-hosted-linux
    outputs:
      build-tag: ${{ steps.generate-build-tag.outputs.build-tag }}
    environment: test
    steps:
      # prebuild
      - name: Checkout code
        uses: actions/checkout@v4
        # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
        with:
          fetch-depth: 0
      - name: Set up JDK${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
      - name: Generate ~/.m2/repository cache key
        id: m2-cache-key
        run: echo "keyname=$(date +'maven-week-%U')" >> $GITHUB_OUTPUT
      - name: Cache ~/.m2/repository
        id: cache-m2-repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ steps.m2-cache-key.outputs.keyname }}
      # build tag
      - name: Generate build tag
        id: generate-build-tag
        run: |
          base_number=$(git describe --abbrev=0 --tags | awk -F \. {'$1++;print $1'})
          echo "Build base_number=$base_number"
          if ! [[ $base_number =~ ^[0-9]+$ ]]; then
            build_tag=$((echo "1" && git rev-parse --short HEAD) | paste -s -d'-'); 
          else 
            build_tag=$((echo $base_number && git rev-parse --short HEAD) | paste -s -d'-'); 
          fi
          echo "Generated build-tag=$build_tag"
          echo "build-tag=$(echo $build_tag)" >> $GITHUB_OUTPUT
      # maven build
      - name: Create m2-settings
        uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d # v22
        with:
          servers: '[
            { "id": "snapshots", "username": "${{ secrets.ARTIFACTORY_USER_NASA }}", "password": "${{ secrets.ARTIFACTORY_PASS_NASA }}" },
            { "id": "releases", "username": "${{ secrets.ARTIFACTORY_USER_NASA }}", "password": "${{ secrets.ARTIFACTORY_PASS_NASA }}" }
          ]'
          repositories: '[
            { "id": "central", "url": "https://repo1.maven.org/maven2/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } },
            { "id": "confluent", "url": "https://packages.confluent.io/maven/" },
            { "id": "jitpack", "url": "https://jitpack.io" },
            { "id": "shibboleth", "url": "https://build.shibboleth.net/nexus/content/repositories/releases/" }
          ]'
          proxies: '[
            { "id": "nb-proxy-http", "active": "true", "protocol": "http", "host": "${{ secrets.PROXY_NB }}", "port": "3128" },
            { "id": "nb-proxy-https", "active": "true", "protocol": "https", "host": "${{ secrets.PROXY_NB }}", "port": "3128" }
          ]'
          output_file: settings.xml
      - name: Download toolchain file

        run: |
          sudo apt-get update && sudo a
          curl https://raw.githubusercontent.com/NationalLibraryOfNorway/nasa-workflows/main/resources/toolchains.xml --output toolchains.xml
      - name: Set maven artifact version
        run: |
          mvn versions:set -DnewVersion="${{ steps.generate-build-tag.outputs.build-tag }}"
          mvn versions:commit
      - name: Build with Maven
        run: mvn --no-transfer-progress --batch-mode --update-snapshots -s settings.xml --global-toolchains toolchains.xml verify
      # docker build
      - name: Build docker image
        run: |
          export DOCKER_POM=`grep -ril "publishRegistry" --include pom.xml`
          if [ $DOCKER_POM ]; then mvn --no-transfer-progress -s settings.xml --global-toolchains toolchains.xml -f $DOCKER_POM spring-boot:build-image -Dmaven.test.skip=true -Ddependency-check.skip=true -Dspring-boot.build-image.publish=true; fi