name: Publish artifact with build-tag to Github package registry

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '21'

jobs:
  build:
    name: Build and publish artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK${{ inputs.java-version }} and cache dependencies
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Set release tag
        run: |
          export MAVEN_VERSION=`mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec | grep -o '[0-9]*\.[0-9]*\.[0-9]*'`
          export RELEASE_VERSION=${MAVEN_VERSION}-${{ github.run_number }}
          echo "Setting Release tag $RELEASE_VERSION"
          mvn versions:set versions:update-child-modules -DnewVersion="${RELEASE_VERSION}"
          mvn versions:commit
      - name: Build with Maven
        run: |
          export DOCKER_POM=`grep -ril "publishRegistry" --include pom.xml`
          mvn -Ddependency-check.skip=true -DskipTests  clean deploy
          if [ $DOCKER_POM ]; then mvn -f $DOCKER_POM spring-boot:build-image -Dmaven.test.skip=true -Ddependency-check.skip=true -Dspring-boot.build-image.publish=true; fi
